export const Links = {
  arrowIcon: "/icons/arrow.webp",
  linkArrowIcon: "/icons/arrowLink.svg",
  downloadIcon: "/icons/downloadIcon.svg",
  diamondIcon: "/icons/diamondStar.svg",
  linkIcon: "/icons/link.svg",
  behanceIcon: "/icons/behance.svg",
  nekorosysIcon: "/icons/nekorosys.svg",
  twitterIcon: "/icons/twitter-x.svg",
  tiktokIcon: "/icons/tiktok.svg",
  kofiIcon: "/icons/kofi.svg",
  paypalIcon: "/icons/paypal.svg",
  bitcoinIcon: "/icons/bitcoin.svg",
  emailIcon: "/icons/email.svg",
  ethereumIcon: "/icons/ethereum.svg",
  instagramIcon: "/icons/instagram.svg",
  payhipIcon: "/icons/payhip.svg",
  facebookIcon: "/icons/facebook.svg",
  youtubeIcon: "/icons/youtube.svg",
  githubIcon: "/icons/github.svg",
  linkedInIcon: "/icons/linkedin.svg",
  discordIcon: "/icons/discord.svg",
  gravensoftIcon: "/icons/gravensoftBgFlat.jpg",
  itchioIcon: "/icons/itchio.svg",
};

export const Stack = {
  figmaIcon: "/icons/techStack/figma.svg",
  canvaIcon: "/icons/techStack/canva.svg",
  affinityIcon: "/icons/techStack/affinity.svg",
  blenderIcon: "/icons/techStack/blender.svg",
  ibispaintIcon: "/icons/techStack/ibispaint.svg",
  alightmotionIcon: "/icons/techStack/alightmotion.svg",
  bashIcon: "/icons/techStack/bash.svg",
  cppIcon: "/icons/techStack/cpp.svg",
  csharpIcon: "/icons/techStack/cs.svg",
  cssIcon: "/icons/techStack/css.svg",
  dockerIcon: "/icons/techStack/docker.svg",
  fastapiIcon: "/icons/techStack/fastapi.svg",
  gitIcon: "/icons/techStack/git.svg",
  githubIcon: "/icons/techStack/github.svg",
  htmlIcon: "/icons/techStack/html.svg",
  javascriptIcon: "/icons/techStack/js.svg",
  kubernetesIcon: "/icons/techStack/k8s.svg",
  linuxIcon: "/icons/techStack/linux.svg",
  mongodbIcon: "/icons/techStack/mongodb.svg",
  nextjsIcon: "/icons/techStack/nextjs.svg",
  nodejsIcon: "/icons/techStack/nodejs.svg",
  pythonIcon: "/icons/techStack/py.svg",
  postgresqlIcon: "/icons/techStack/postgresql.svg",
  reactIcon: "/icons/techStack/react.svg",
  tailwindIcon: "/icons/techStack/tailwind.svg",
  typescriptIcon: "/icons/techStack/ts.svg",
  unityIcon: "/icons/techStack/unity.svg",
  vercelIcon: "/icons/techStack/vercel.svg",
  viteIcon: "/icons/techStack/vite.png",
  vscodeIcon: "/icons/techStack/vscode.svg",
};

export const Media = {
  nekorosysBanner: "/images/nekorosys/bannerSmall.png",
};
