export const Icons = {
  arrowIcon: "/icons/arrow.webp",
  diamondIcon: "/icons/DiamondStar.png",
  linkIcon: "/icons/link.svg",
  behanceIcon: "/icons/behance.svg",
  twitterIcon: "/icons/twitter-x.svg",
  tiktokIcon: "/icons/tiktok.svg",
  kofiIcon: "/icons/kofi.svg",
  paypalIcon: "/icons/paypal.svg",
  bitcoinIcon: "/icons/bitcoin.svg",
  emailIcon: "/icons/email.svg",
  ethereumIcon: "/icons/ethereum.svg",
  instagramIcon: "/icons/instagram.svg",
  payhipIcon: "/icons/payhip.svg",
  facebookIcon: "/icons/facebook.svg",
  youtubeIcon: "/icons/youtube.svg",
  githubIcon: "/icons/github.svg",
  linkedInIcon: "/icons/linkedin.svg",
  discordIcon: "/icons/discord.svg",
  gravensoftIcon: "/icons/gravensoftBgFlat.jpg",
  itchioIcon: "/icons/itchio.svg",
};
